language: rust
rust:
  - nightly

after_success: |
    cargo doc --no-deps --verbose \
    && echo '<meta http-equiv=refresh content=0;url=a_fractal_a_day/index.html>' > target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc
  on:
    branch: master
