[package]
name = "a_fractal_a_day"
version = "0.1.0"
authors = ["Hendrik Schawe <surt91@gmail.com>"]

[dependencies]
png = "*"
num = "*"
rand = "*"
itertools = "*"
rayon = "*"
time = "*"

json = "*"
tweetust = "*"
