[package]
name = "a_fractal_a_day"
version = "0.1.0"
authors = ["Hendrik Schawe <surt91@gmail.com>"]
description = "This is a Twitter bot, which can tweet pictures of random fractals."
homepage = "https://twitter.com/AFractalADay"

[[bin]]
name = "a_fractal_a_day"
doc = false

[dependencies]
png = "*"
num = "*"
rand = "*"
itertools = "*"
rayon = "*"
num_cpus = "*"
time = "*"
clap = "*"
log = "*"
simplelog = "*"
log-panics = "*"

[dependencies.my_twitter]
path = "my_twitter"
