[package]
name = "my_twitter"
version = "0.2.0"
authors = ["Hendrik Schawe <surt91@gmail.com>"]

[dependencies]
json = "*"
tokio = "*"
# egg-mode = "0.12.0"

[dependencies.egg-mode]
version = "*"
git = "https://github.com/QuietMisdreavus/twitter-rs"
